export const users = [
    {
        "id": 1,
        "name": "Leonardo",
        "lastname": "García",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "04-05-2024",
        "status": "Duedate Soon"
    },
    {
        "id": 2,
        "name": "Sofía",
        "lastname": "Sánchez ",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "15-11-2024",
        "status": "Duedate"
    },
    {
        "id": 3,
        "name": "Sofía",
        "lastname": "González ",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "04-05-2024",
        "status": "Duedate Soon"
    },
    {
        "id": 4,
        "name": "Santiago",
        "lastname": "Castillo",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "03-09-2024",
        "status": "Duedate"
    },
    {
        "id": 5,
        "name": "Sebastián",
        "lastname": "López",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "03-08-2024",
        "status": "Active"
    },
    {
        "id": 6,
        "name": "Alexander",
        "lastname": "López",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "08-11-2024",
        "status": "Duedate"
    },
    {
        "id": 7,
        "name": "Emiliano",
        "lastname": "Castillo",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "14-09-2024",
        "status": "Active"
    },
    {
        "id": 8,
        "name": "Alexander",
        "lastname": "Álvarez",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "18-05-2024",
        "status": "Duedate Soon"
    },
    {
        "id": 9,
        "name": "Santiago",
        "lastname": "García",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "18-08-2024",
        "status": "Active"
    },
    {
        "id": 10,
        "name": "María Fernanda",
        "lastname": "López",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "06-04-2024",
        "status": "Active"
    },
    {
        "id": 11,
        "name": "Santiago",
        "lastname": "Hernández",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "05-09-2024",
        "status": "Active"
    },
    {
        "id": 12,
        "name": "María José",
        "lastname": "García",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "13-11-2024",
        "status": "Active"
    },
    {
        "id": 13,
        "name": "Leonardo",
        "lastname": "González ",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "14-01-2024",
        "status": "Active"
    },
    {
        "id": 14,
        "name": "Leonardo",
        "lastname": "Rodríguez ",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "05-04-2024",
        "status": "Duedate"
    },
    {
        "id": 15,
        "name": "Alexander",
        "lastname": "López",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "11-00-2024",
        "status": "Active"
    },
    {
        "id": 16,
        "name": "Regina",
        "lastname": "Castillo",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "01-02-2024",
        "status": "Duedate"
    },
    {
        "id": 17,
        "name": "Valentina",
        "lastname": "González ",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "02-01-2024",
        "status": "Duedate Soon"
    },
    {
        "id": 18,
        "name": "Regina",
        "lastname": "Rodríguez ",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "11-02-2024",
        "status": "Duedate"
    },
    {
        "id": 19,
        "name": "Alexander",
        "lastname": "López",
        "birthday": "",
        "service": "Gym",
        "image": "",
        "amount": 500,
        "duedate": "05-00-2024",
        "status": "Active"
    }
];